# Generated by Django 5.1.2 on 2025-01-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name="Номер телефона"),
        ),
    ]
