# Generated by Django 5.1.2 on 2025-02-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_allowedperson_rename_medium_name_user_middle_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedperson',
            options={'ordering': ['last_name'], 'verbose_name': 'Разрешенный пользователь', 'verbose_name_plural': 'Разрешенные пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
