# Generated by Django 5.1.2 on 2024-11-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoMFSS", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DateUpdate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("update", models.DateTimeField(blank=True, null=True, verbose_name="Дата обновления данных")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Краткое описание")),
            ],
            options={
                "verbose_name": "дата последнего изменения",
                "verbose_name_plural": "даты последнего изменения",
            },
        ),
    ]
