# Generated by Django 5.1.2 on 2024-11-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("infoMFSS", "0002_dateupdate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dateupdate",
            options={
                "ordering": ["-update"],
                "verbose_name": "дата последнего изменения",
                "verbose_name_plural": "даты последнего изменения",
            },
        ),
    ]
