# Generated by Django 5.1.2 on 2024-11-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoMFSS", "0003_alter_dateupdate_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="tunnel",
            name="name_slag",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Генерация slag"),
        ),
    ]
