# Generated by Django 5.1.2 on 2024-11-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoMFSS', '0004_tunnel_name_slag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execution',
            options={'ordering': ['equipment_install'], 'verbose_name': 'выполнение работы', 'verbose_name_plural': 'отчет выполнения работ'},
        ),
        migrations.AddField(
            model_name='equipmentinstallation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Обозначение в проекте'),
        ),
    ]
