# Generated by Django 5.1.2 on 2024-11-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoMFSS', '0007_alter_execution_number_mine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execution',
            name='inclined_blocks',
        ),
        migrations.RemoveField(
            model_name='execution',
            name='number_mine',
        ),
        migrations.RemoveField(
            model_name='execution',
            name='subsystem',
        ),
    ]
