# Generated by Django 5.1.2 on 2024-11-09 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoMFSS", "0008_remove_execution_inclined_blocks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="execution",
            name="cable_magazine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cable_executions",
                to="infoMFSS.cablemagazine",
                verbose_name="Список трасс кабелей",
            ),
        ),
        migrations.AlterField(
            model_name="execution",
            name="equipment_install",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eq_executions",
                to="infoMFSS.equipmentinstallation",
                verbose_name="Список оборудования",
            ),
        ),
    ]
