# Generated by Django 5.1.2 on 2024-11-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoMFSS', '0009_alter_execution_cable_magazine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbermine',
            name='title',
            field=models.CharField(choices=[('Нефтешахта №1', 'Нефтешахта №1'), ('Нефтешахта №2', 'Нефтешахта №2'), ('Нефтешахта №3', 'Нефтешахта №3'), ('', '')], max_length=15, verbose_name='Шахта'),
        ),
        migrations.AlterField(
            model_name='tunnel',
            name='inclined_bool',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак уклонного блока'),
        ),
        migrations.AlterField(
            model_name='tunnel',
            name='tuf_bool',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак туффитового горизонта'),
        ),
    ]
