# Generated by Django 5.1.2 on 2024-12-12 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoMFSS', '0019_branchesbox_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchesbox',
            name='slug',
        ),
    ]
