# Generated by Django 5.1.2 on 2024-12-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("infoMFSS", "0021_equipmentinstallation_equipment_bool"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tunnel",
            name="slug",
        ),
    ]
