# Generated by Django 5.1.2 on 2024-12-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoMFSS', '0022_remove_tunnel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointphone',
            name='subscriber_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Абонентский номер'),
        ),
    ]
