# Generated by Django 5.1.2 on 2025-01-02 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoMFSS', '0025_alter_pointphone_options_equipment_file_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='subsystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsystem_cable', to='infoMFSS.subsystem', verbose_name='Подсистема'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='subsystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsystem_equipment', to='infoMFSS.subsystem', verbose_name='Подсистема'),
        ),
    ]
