# Generated by Django 5.1.2 on 2025-01-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoMFSS", "0027_cable_file_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="cable",
            name="file_certificate",
            field=models.FileField(default=1, upload_to="pdf_certificate"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="equipment",
            name="file_certificate",
            field=models.FileField(default=1, upload_to="pdf_certificate"),
            preserve_default=False,
        ),
    ]
