# Generated by Django 5.1.2 on 2025-01-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoMFSS", "0030_violations"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentinstallation",
            name="file_graphics",
            field=models.FileField(blank=True, null=True, upload_to="pdf_graphics"),
        ),
    ]
