# Generated by Django 5.1.2 on 2025-01-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoMFSS", "0036_alter_visual_equipment_alter_visual_number_mines_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visual",
            name="equipment",
            field=models.CharField(
                choices=[
                    (None, "Выберите один из пунктов списка"),
                    ("Телефоны", "Телефоны"),
                    ("Респред.коробки", "Распред.коробки"),
                    ("Датчики ПДК", "Датчики ПДК"),
                    ("Станции связи", "Станции связи"),
                    ("Точки доступа wi-fi", "Точки доступа wi-fi"),
                    ("Видеокамеры", "Видеокамеры"),
                ],
                max_length=50,
                verbose_name="Оборудование",
            ),
        ),
        migrations.AlterField(
            model_name="visual",
            name="number_mines",
            field=models.CharField(
                choices=[
                    (None, "Выберите один из пунктов списка"),
                    ("Нефтешахта №1", "Нефтешахта №1"),
                    ("Нефтешахта №2", "Нефтешахта №2"),
                    ("Нефтешахта №3", "Нефтешахта №3"),
                ],
                max_length=15,
                verbose_name="Шахта",
            ),
        ),
        migrations.AlterField(
            model_name="visual",
            name="subsystems",
            field=models.CharField(
                choices=[
                    (None, "Выберите один из пунктов списка"),
                    ("АТС", "АТС"),
                    ("АГК", "АГК"),
                    ("Позиционирование", "Позиционирование"),
                    ("Видеонаблюдение", "Видеонаблюдение"),
                ],
                max_length=20,
                verbose_name="Подсистема",
            ),
        ),
    ]
