# Generated by Django 5.1.2 on 2025-01-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoMFSS', '0038_cablemagazine_cable_bool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointphone',
            name='picket',
        ),
    ]
