# Generated by Django 5.1.2 on 2025-01-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoMFSS', '0039_remove_pointphone_picket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointphone',
            name='inclined_blocks',
        ),
        migrations.RemoveField(
            model_name='pointphone',
            name='tunnel',
        ),
    ]
