# Generated by Django 5.1.2 on 2025-02-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoMFSS', '0045_alter_equipment_file_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='file_certificate',
            field=models.FileField(blank=True, null=True, upload_to='pdf_certificate', verbose_name='Сертификат'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='file_passport',
            field=models.FileField(blank=True, null=True, upload_to='pdf_passport', verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='file_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf', verbose_name='Руководство по эксплуатации'),
        ),
    ]
