# Generated by Django 5.1.2 on 2025-03-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoMFSS", "0054_alter_cablemagazine_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="violations",
            name="file_act",
            field=models.FileField(blank=True, null=True, upload_to="Акт"),
        ),
        migrations.AlterField(
            model_name="violations",
            name="file_notification",
            field=models.FileField(blank=True, null=True, upload_to="Уведомление об устранении"),
        ),
    ]
