# Generated by Django 5.1.2 on 2025-03-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoMFSS', '0056_alter_violations_file_act_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violations',
            name='file_act',
            field=models.FileField(blank=True, null=True, upload_to='pdf_act', verbose_name='Акт'),
        ),
        migrations.AlterField(
            model_name='violations',
            name='file_notification',
            field=models.FileField(blank=True, null=True, upload_to='pdf_notifications', verbose_name='Уведомление'),
        ),
    ]
