# Generated by Django 5.1.2 on 2025-03-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoMFSS', '0057_alter_violations_file_act_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violations',
            name='execution_bool',
            field=models.BooleanField(default=False, verbose_name='Предписание исполнено'),
        ),
    ]
