# Generated by Django 5.1.2 on 2025-03-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoMFSS', '0059_alter_violations_execution_bool'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visual',
        ),
    ]
