# Generated by Django 5.1.2 on 2025-03-02 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoMFSS", "0060_delete_visual"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visual",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_pdf", models.FileField(blank=True, null=True, upload_to="pdf_visual", verbose_name="Файл pdf")),
                ("data", models.DateTimeField(auto_now=True, verbose_name="Дата изменения")),
                (
                    "cable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cable_visual",
                        to="infoMFSS.cable",
                        verbose_name="Кабель",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_visual",
                        to="infoMFSS.equipment",
                        verbose_name="Оборудование",
                    ),
                ),
                (
                    "number_mine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mine_visual",
                        to="infoMFSS.numbermine",
                        verbose_name="Шахта",
                    ),
                ),
                (
                    "subsystem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_visual",
                        to="infoMFSS.subsystem",
                        verbose_name="Подсистема",
                    ),
                ),
            ],
            options={
                "verbose_name": "визуализация",
                "verbose_name_plural": "визуализации",
                "ordering": ["number_mine"],
            },
        ),
    ]
