# Generated by Django 5.1.2 on 2025-03-25 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("infoMFSS", "0062_alter_equipmentinstallation_subsystem_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipmentinstallation",
            options={
                "ordering": ["-id"],
                "verbose_name": "место установки оборудования",
                "verbose_name_plural": "места установки оборудования",
            },
        ),
    ]
