# Generated by Django 5.1.2 on 2025-04-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoMFSS", "0070_alter_dateupdate_update_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="device_type",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Тип"),
        ),
    ]
