# Generated by Django 5.1.2 on 2025-04-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoMFSS", "0071_equipment_device_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="cable",
            name="device_type",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Тип"),
        ),
    ]
