# Generated by Django 5.1.2 on 2025-04-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoMFSS", "0072_cable_device_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="title",
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Оборудование"),
        ),
    ]
