# Generated by Django 5.1.2 on 2025-05-02 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoMFSS", "0073_alter_equipment_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cablemagazine",
            name="track_from_box",
        ),
        migrations.RemoveField(
            model_name="cablemagazine",
            name="track_to_box",
        ),
        migrations.RemoveField(
            model_name="cablemagazine",
            name="track_to_phone",
        ),
        migrations.AlterField(
            model_name="cablemagazine",
            name="track_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="track_from",
                to="infoMFSS.equipmentinstallation",
                verbose_name="От оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="cablemagazine",
            name="track_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="track_to",
                to="infoMFSS.equipmentinstallation",
                verbose_name="До оборудования",
            ),
        ),
    ]
