# Generated by Django 5.1.2 on 2025-05-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoMFSS", "0074_remove_cablemagazine_track_from_box_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beacon",
            name="data",
            field=models.DateField(auto_now=True, verbose_name="Дата монтажа"),
        ),
    ]
