# Generated by Django 5.1.2 on 2025-05-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoMFSS", "0075_beacon_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beacon",
            name="data",
            field=models.DateField(verbose_name="Дата монтажа"),
        ),
    ]
